version: '3.8'

services:
  app:
    build: .
    container_name: scisynth-app
    ports:
      - "8501:8501"
    depends_on:
      - chromadb
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ENABLECORS=false
    volumes:
      - .:/app
      - ./data:/app/data
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    container_name: scisynth-chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./data/chroma_db:/chroma/chroma/
    environment:
      - IS_PERSISTENT=TRUE
    restart: unless-stopped

  # Placeholder for future services (e.g., API, worker)
  # api:
  #   build: ./api
  #   ports:
  #     - "8001:8001"
  #   depends_on:
  #     - chromadb 