name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - '**/*.md'
      - 'docs/**'
      - '.github/workflows/docs-deploy.yml'

# Add permissions for GitHub Pages deployment
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.lock
          pip install pdoc3 mkdocs-material

      - name: Generate API Documentation
        run: |
          # Create docs directory if it doesn't exist
          mkdir -p docs/api
          
          # Generate API docs
          pdoc --html --output-dir docs/api app/ agents/ logic/ evolutionary/ utils/ || echo "Warning: Some modules may not have generated docs"
          
          # Create index page
          cat > docs/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>SciSynth AI - Documentation</title>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <style>
                  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
                  .container { max-width: 1200px; margin: 0 auto; background: white; padding: 40px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
                  h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
                  .section { margin: 30px 0; }
                  .card { background: #f8f9fa; padding: 20px; border-radius: 6px; margin: 15px 0; border-left: 4px solid #3498db; }
                  .btn { display: inline-block; padding: 12px 24px; background: #3498db; color: white; text-decoration: none; border-radius: 6px; margin: 10px 5px; }
                  .btn:hover { background: #2980b9; }
                  .badge { background: #27ae60; color: white; padding: 4px 8px; border-radius: 12px; font-size: 12px; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🧪 SciSynth AI Research Assistant</h1>
                  <p><strong>Enterprise-Grade AI System for Scientific Literature Analysis</strong></p>
                  
                  <div class="section">
                      <h2>📚 Documentation</h2>
                      <div class="card">
                          <h3>🔗 API Documentation</h3>
                          <p>Complete API reference for all modules and functions.</p>
                          <a href="./api/" class="btn">View API Docs</a>
                      </div>
                  </div>
                  
                  <div class="section">
                      <h2>🚀 Quick Start</h2>
                      <div class="card">
                          <h3>🐳 Docker Deployment</h3>
                          <code>docker run -p 8501:8501 avinash76543/scisynth-ai:latest</code>
                          <br><br>
                          <a href="https://github.com/Avinash291020/SciSynth-AI-Research-Assistant" class="btn">View on GitHub</a>
                          <a href="https://hub.docker.com/r/avinash76543/scisynth-ai" class="btn">Docker Hub</a>
                      </div>
                  </div>
                  
                  <div class="section">
                      <h2>🔒 Security & Compliance</h2>
                      <div class="card">
                          <p><span class="badge">✅</span> Automated vulnerability scanning</p>
                          <p><span class="badge">✅</span> SBOM generation</p>
                          <p><span class="badge">✅</span> Non-root container execution</p>
                          <p><span class="badge">✅</span> Version-pinned dependencies</p>
                      </div>
                  </div>
                  
                  <div class="section">
                      <h2>🧠 AI Capabilities</h2>
                      <div class="card">
                          <p><strong>Multi-Paradigm AI System:</strong></p>
                          <p>• LLM & RAG (Retrieval-Augmented Generation)</p>
                          <p>• Reinforcement Learning (RL)</p>
                          <p>• Evolutionary Algorithms</p>
                          <p>• Symbolic & Neuro-Symbolic AI</p>
                          <p>• Agentic AI & Cognitive Planning</p>
                      </div>
                  </div>
                  
                  <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #666;">
                      <p>Built with enterprise DevSecOps practices | <a href="https://github.com/Avinash291020/SciSynth-AI-Research-Assistant">GitHub</a></p>
                  </footer>
              </div>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true 