name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - '**/*.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.py'
      - '**/*.md'
      - 'docs/**'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pdoc3 black

    - name: Generate documentation
      run: |
        pdoc --html --output-dir docs/ app/ agents/ logic/ evolutionary/ utils/

    - name: Format Python files
      run: |
        black .

    - name: Check for documentation changes
      id: docs-check
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "::set-output name=changes::true"
        else
          echo "::set-output name=changes::false"
        fi

    - name: Commit documentation changes
      if: steps.docs-check.outputs.changes == 'true' && github.event_name == 'push'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git add *.py
        git commit -m "Auto-update documentation and format code"
        git push 